// app/layout.tsx
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; // ⬅️ Make sure this path is correct

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider> {/* ✅ Wrap your app in AuthProvider */}
      </body>
    </html>
  );
}
